# Generated by Django 2.2.1 on 2019-05-20 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condo_app', '0003_condo_facility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condo',
            name='superuser',
        ),
        migrations.AddField(
            model_name='condo',
            name='condo_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
