# Generated by Django 2.2.1 on 2019-05-20 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condo_app', '0004_auto_20190520_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='open_time',
            new_name='first_booking_time',
        ),
    ]
