# Generated by Django 2.2.1 on 2019-05-20 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condo_app', '0005_auto_20190520_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='close_time',
            new_name='last_booking_time_time',
        ),
    ]
