# Generated by Django 2.2.1 on 2019-05-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condo_app', '0007_auto_20190520_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='condo',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
