# Generated by Django 2.2.1 on 2019-05-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condo_app', '0008_auto_20190520_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condo',
            name='address',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
